### ISSUE TITLE
blocking versioned image, signature, etc

### ISSUE THREAD

**Issue by stephane-couget** [ishafiul/flutter_img#2]
Good morning,
The command flutter pub get returns me this:

Because flutter_img 0.0.3 depends on flutter_svg ^1.1.6 and no versions of flutter_img match >0.0.3 <0.1.0, flutter_img ^0.0.3 requires flutter_svg ^1.1.6.
So, because TDC_RapVerif depends on both flutter_img ^0.0.3 and flutter_svg ^2.0.6, version solving failed.

Is it possible to upgrade the version of flutter_svg to 2.0.6 instead of 1.1.6 please?

Best regards,
Stéphane

**Comment by ishafiul** [comment]
hope 0.1.0 will solve your problem
